### PR TITLE
Normalize discovered URIs before comparing them

### PR DESCRIPTION
**Pull request by cjwatson**
python-openid2's urinorm is stricter than that in the old Python-2-only
version: in particular, it always normalizes the reserved character '+'
to '%2B'.  The discovery process normalizes URIs, so
GenericConsumer._verifyDiscoverySingle could end up comparing normalized
and unnormalized identifiers.

In particular, this broke with the Ubuntu single-sign-on system
(login.ubuntu.com / login.launchpad.net) which includes a '+' character
in the path part of its identifiers.

It makes sense to normalize both expected and discovered identifiers
before comparing them, so do that according to the rules in OpenID
Authentication 2.0 section 7.2.

### CODE REVIEW

**Comment by cjwatson** [comment]
#42 fixes the CI failures here.  I plan to rebase this once that PR lands.

**Comment by cjwatson** [comment]
Rebased now, so CI should be happy shortly.

**Comment by cjwatson** [comment]
@ziima @tpazderka Would there be any chance of getting a review of this, please?  I have I think three other projects so far that are blocked on this as part of their Python 3 upgrades.

**Comment by ziima** [comment]
Sorry about the delay and thanks for poking us :-)

I believe the cause is in the `urinorm` itself, so I prepared a fix only for that in #43. I'd appreciate if you could check that it really helps with this issue.

**Comment by cjwatson** [comment]
@ziima #43 seems to fix my problem just as well, so I'm happy with that.  Thanks!

**Comment by ziima** [comment]
Closing, since #43 fixed the issue.

**Pull request closed without merging**
